CREATE  TABLE IF NOT EXISTS `atk_video` (
  `id` INT(11) NOT NULL AUTO_INCREMENT ,
  `name` VARCHAR(255) NULL DEFAULT NULL ,
  `is_public` ENUM('Y','N') NULL DEFAULT NULL ,
  `src` VARCHAR(255) NULL DEFAULT NULL ,
  `descr` TEXT NULL DEFAULT NULL ,
  `type` VARCHAR(45) NULL DEFAULT NULL ,
  PRIMARY KEY (`id`) ,
  INDEX `type` (`type` ASC) )
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;

ALTER TABLE `atk_video` 
    ADD COLUMN `atk_version` VARCHAR(45) NULL DEFAULT NULL  AFTER `type` , 
    ADD COLUMN `complexity` VARCHAR(45) NULL DEFAULT NULL  AFTER `atk_version` ;

ALTER TABLE `atk_video`
    ADD COLUMN `ord` INT(11) NULL DEFAULT NULL  AFTER `id` ;

